### PR TITLE
Esteban biz fn 1.2

### PR DESCRIPTION
**Pull request by esteban-gs**
- Made all necessary changes to work with my existing config file from the wn19 app.

- Fixed the object issue.

- Improved some comments

### CODE REVIEW

**Comment by esteban-gs** [comment]
Please review, merge to master and delete old branch.

**Review by thomaskise — APPROVED** [review]
This looks good. Lloks like my faux pas on the new items. Thanks for catching that!

**Comment by thomaskise** [comment]
Fabulous! works perfect.
https://kiseharrington.com/wn19test/food/index.php

Now I'd like to make one more change. I'd like to add a "food" folder to
the repo .. win19/food/ and move the index.php and items.php into it.
 Then it will match our website schema.  What do you thing?

**Comment by esteban-gs** [comment]
I think it should work

**Comment by thomaskise** [comment]
Sounds like a go.  I can do it now.

**Comment by thomaskise** [comment]
Done.  Looks great. Now we can work on adding up the sub totals, and making
it look a little prettier.

Hope Jeneva was able to to get in touch with Yonny on the compliance
review.

**Pull request merged**
