### PR TITLE
fix html and delete extraneous file

### PR DESCRIPTION
**Pull request by thomaskise**
Fixed three invalid script references
deleted unneeded function call
Deleted extraneous copy of index.php from the includes folder

Anyone can review & merge.

### CODE REVIEW

**Comment by esteban-gs** [comment]
I won't be able to review until after work at around 8 pm.

**Comment by thomaskise** [comment]
Closing this request to add additional changes

**Comment by thomaskise** [comment]
Fixes all the header.php issues in iissue #23

**Comment by thomaskise** [comment]
closes issue #25 consider moving function. Function was not needed and deleted.

**Pull request merged**
